# PAMCA Infrared Spectrosocpy and Machine Learning Workshop

## Assigment and grading:

This is the assignment on Basics of Python and Spectroscopy. 
- There are 10 questions related to python and one excercise about spectroscopy. 
- Type your name in the assigned cell.
- Please type your answers in the space provided (indicated with the message: type your answer here). After you type your answers, run the cells to make sure there are no errors. 


The deadline for this assignment will be on **Wednesday 7th May from 11:00 - 13:00 UK time** (**assignments send later than 13:00 will not be graded**) You need to send it to my email: mauro.pazminobetancourth@glasgow.ac.uk. I will upload the jupyter notebook with the solutions on Wednesday after the deadline (as preparation for the next sessions).


This assignment is graded and it will be part of your final grade for this course. 



- Please type your name here:  TUHAISE VIOLET

## Assesment Python

### Instructions:
For this part you need to download the file: IR_dataset_PAMCA.csv located in the dataset folder in TEAMS. Please download the file into your working folder.

**About the data set**

The dataset is made of infrared spectroscopy measurements of mosquito samples from University of Glasgow. It has samples from two different species and measured them at different chronological ages. 

In [1]:
# Import the following packages

import pandas as pd
import numpy as np


1. Import the dataset IR_dataset_PAMCA.csv using pandas and called df_mosquitoes.

In [2]:
## type your answer here
df_mosquitoes = pd.read_csv(r"C:\Users\user\Downloads\IR_dataset_PAMCA.csv")

2. Print the first 10 rows. 

In [3]:
## type your answer here

print(df_mosquitoes.head(10))

  spcs  Age      Dataset Status Country RearCnd  StoTime    1800    1798  \
0   AC    1  Glasgow Lab     SF       S      TL       83  0.0105  0.0106   
1   AC    1  Glasgow Lab     SF       S      TL       83  0.0105  0.0106   
2   AC    1  Glasgow Lab     SF       S      TL       83  0.0094  0.0094   
3   AC    1  Glasgow Lab     SF       S      TL       83  0.0094  0.0094   
4   AC    1  Glasgow Lab     SF       S      TL       83  0.0116  0.0117   
5   AC    1  Glasgow Lab     SF       S      TL       83  0.0116  0.0117   
6   AC    1  Glasgow Lab     SF       S      TL       83  0.0122  0.0123   
7   AC    1  Glasgow Lab     SF       S      TL       83  0.0122  0.0123   
8   AC    1  Glasgow Lab     SF       S      TL       83  0.0134  0.0136   
9   AC    1  Glasgow Lab     SF       S      TL       83  0.0134  0.0136   

     1796  ...     620     618     616     614     612     610     608  \
0  0.0107  ...  0.1472  0.1478  0.1478  0.1475  0.1476  0.1481  0.1489   
1  0.0107  ... 

2. Rename the following columns and print the first 10 rows: 
    - spcs to Species
    - RearCnd to Rear Conditions 

In [4]:
## type your answer here

df_mosquitoes.rename(columns={"spcs":"Species", "RearCnd":"Rear Condition"}, inplace=True)
print(df_mosquitoes.head(10))

  Species  Age      Dataset Status Country Rear Condition  StoTime    1800  \
0      AC    1  Glasgow Lab     SF       S             TL       83  0.0105   
1      AC    1  Glasgow Lab     SF       S             TL       83  0.0105   
2      AC    1  Glasgow Lab     SF       S             TL       83  0.0094   
3      AC    1  Glasgow Lab     SF       S             TL       83  0.0094   
4      AC    1  Glasgow Lab     SF       S             TL       83  0.0116   
5      AC    1  Glasgow Lab     SF       S             TL       83  0.0116   
6      AC    1  Glasgow Lab     SF       S             TL       83  0.0122   
7      AC    1  Glasgow Lab     SF       S             TL       83  0.0122   
8      AC    1  Glasgow Lab     SF       S             TL       83  0.0134   
9      AC    1  Glasgow Lab     SF       S             TL       83  0.0134   

     1798    1796  ...     620     618     616     614     612     610  \
0  0.0106  0.0107  ...  0.1472  0.1478  0.1478  0.1475  0.1476  0.1

3. Print the classes and the number of samples that are in column Status

In [5]:
## type your answer here
print(df_mosquitoes["Status"])


0       SF
1       SF
2       SF
3       SF
4       SF
        ..
1659    SF
1660    SF
1661    SF
1662    SF
1663    SF
Name: Status, Length: 1664, dtype: object


In [6]:
df_mosquitoes["Status"].value_counts()

Status
SF    904
BF    436
GR    324
Name: count, dtype: int64

In [7]:
df_mosquitoes["Status"].value_counts().sort_index()

Status
BF    436
GR    324
SF    904
Name: count, dtype: int64

4. Print the classes and the number of samples that exist in the column **Age**. The values should be sort by values (smallest to the greatest)

In [8]:
## type you answer here
print(df_mosquitoes["Age"])

0        1
1        1
2        1
3        1
4        1
        ..
1659    10
1660    10
1661    10
1662    10
1663    10
Name: Age, Length: 1664, dtype: int64


In [9]:
df_mosquitoes["Age"].value_counts().sort_index()

Age
1     254
3     207
5     300
7     311
9     279
10    313
Name: count, dtype: int64

5. Select the samples that have values less than 0.1336 at the wavelenght 612

In [10]:
## type your answer here

df_mosquitoes[(df_mosquitoes["612"] < 0.1336)]

Species  Age      Dataset Status Country Rear Condition  StoTime    1800  \
2         AC    1  Glasgow Lab     SF       S             TL       83  0.0094   
3         AC    1  Glasgow Lab     SF       S             TL       83  0.0094   
14        AC    1  Glasgow Lab     SF       S             TL       83  0.0109   
15        AC    1  Glasgow Lab     SF       S             TL       83  0.0109   
16        AC    1  Glasgow Lab     SF       S             TL       83  0.0098   
...      ...  ...          ...    ...     ...            ...      ...     ...   
1194      AG    5  Glasgow Lab     SF       S             TL        9  0.0110   
1270      AG    7  Glasgow Lab     BF       S             TL       13  0.0118   
1455      AG    9  Glasgow Lab     SF       S             TL        8  0.0072   
1479      AG    9  Glasgow Lab     SF       S             TL        8  0.0105   
1551      AG   10  Glasgow Lab     BF       S             TL        9  0.0103   

        1798    1796  ...     620     618     616     614     612     610  \
2     0.0094  0.0094  ...  0.1044  0.1045  0.1047  0.1051  0.1054  0.1057   
3     0.0094  0.0094  ...  0.1044  0.1045  0.1047  0.1051  0.1054  0.1057   
14    0.0108  0.0106  ...  0.1288  0.1291  0.1295  0.1301  0.1307  0.1313   
15    0.0108  0.0106  ...  0.1288  0.1291  0.1295  0.1301  0.1307  0.1313   
16    0.0098  0.0098  ...  0.0976  0.0978  0.0981  0.0984  0.0987  0.0989   
...      ...     ...  ...     ...     ...     ...     ...     ...     ...   
1194  0.0112  0.0112  ...  0.1100  0.1102  0.1105  0.1108  0.1113  0.1118   
1270  0.0118  0.0118  ...  0.1086  0.1089  0.1092  0.1095  0.1098  0.1100   
1455  0.0073  0.0073  ...  0.1230  0.1235  0.1241  0.1247  0.1253  0.1260   
1479  0.0106  0.0106  ...  0.1258  0.1264  0.1269  0.1273  0.1278  0.1283   
1551  0.0104  0.0105  ...  0.1280  0.1282  0.1284  0.1286  0.1288  0.1291   

         608     606     604     602  
2     0.1060  0.1064  0.1068  0.1074  
3     0.1060  0.1064  0.1068  0.1074  
14    0.1321  0.1330  0.1337  0.1345  
15    0.1321  0.1330  0.1337  0.1345  
16    0.0991  0.0993  0.0996  0.1001  
...      ...     ...     ...     ...  
1194  0.1122  0.1125  0.1130  0.1136  
1270  0.1103  0.1106  0.1109  0.1114  
1455  0.1266  0.1272  0.1278  0.1285  
1479  0.1288  0.1293  0.1297  0.1301  
1551  0.1295  0.1300  0.1305  0.1312  

[89 rows x 607 columns]

6. Replace the following values: 
    - AC: An. coluzzii
    - AG: An. gambiae
    - SF: Sugar fed
    - BF: Blood fed
    - GR: Gravid

In [20]:
## print your answer here

replace_values_1={"AC":"An. coluzzii", "AG": "An. gambiae"} 
replace_values_2={"SF":"Sugar fed", "BF":"Blood fed", "GR":"Gravid"}
df_mosquitoes.replace({"Species":  replace_values_1, "Status": replace_values_2}, inplace = True)
df_mosquitoes.head()

Species  Age      Dataset     Status Country Rear Condition  StoTime  \
0  An. coluzzii    1  Glasgow Lab  Sugar fed       S             TL       83   
1  An. coluzzii    1  Glasgow Lab  Sugar fed       S             TL       83   
2  An. coluzzii    1  Glasgow Lab  Sugar fed       S             TL       83   
3  An. coluzzii    1  Glasgow Lab  Sugar fed       S             TL       83   
4  An. coluzzii    1  Glasgow Lab  Sugar fed       S             TL       83   

     1800    1798    1796  ...     620     618     616     614     612  \
0  0.0105  0.0106  0.0107  ...  0.1472  0.1478  0.1478  0.1475  0.1476   
1  0.0105  0.0106  0.0107  ...  0.1472  0.1478  0.1478  0.1475  0.1476   
2  0.0094  0.0094  0.0094  ...  0.1044  0.1045  0.1047  0.1051  0.1054   
3  0.0094  0.0094  0.0094  ...  0.1044  0.1045  0.1047  0.1051  0.1054   
4  0.0116  0.0117  0.0118  ...  0.1322  0.1325  0.1328  0.1332  0.1336   

      610     608     606     604     602  
0  0.1481  0.1489  0.1497  0.1507  0.1519  
1  0.1481  0.1489  0.1497  0.1507  0.1519  
2  0.1057  0.1060  0.1064  0.1068  0.1074  
3  0.1057  0.1060  0.1064  0.1068  0.1074  
4  0.1341  0.1349  0.1357  0.1365  0.1376  

[5 rows x 607 columns]

7. Create a new variable called ac_bf and assigned to it all the samples that are An. coluzzii and Blood fed and print the first 5 rows.

In [12]:
## print your answer here
ac_bf =  df_mosquitoes[(df_mosquitoes['Species'] == 'An. coluzzii') & (df_mosquitoes['Status'] == 'Blood fed')]
ac_bf.head()

Species  Age      Dataset     Status Country Rear Condition  StoTime  \
80  An. coluzzii    3  Glasgow Lab  Blood fed       S             TL       96   
81  An. coluzzii    3  Glasgow Lab  Blood fed       S             TL       96   
82  An. coluzzii    3  Glasgow Lab  Blood fed       S             TL       96   
83  An. coluzzii    3  Glasgow Lab  Blood fed       S             TL       96   
84  An. coluzzii    3  Glasgow Lab  Blood fed       S             TL       96   

      1800    1798    1796  ...     620     618     616     614     612  \
80  0.0100  0.0101  0.0104  ...  0.1388  0.1394  0.1397  0.1400  0.1405   
81  0.0126  0.0128  0.0132  ...  0.1611  0.1620  0.1627  0.1634  0.1640   
82  0.0111  0.0112  0.0114  ...  0.1442  0.1449  0.1454  0.1459  0.1463   
83  0.0122  0.0123  0.0126  ...  0.1017  0.1022  0.1026  0.1029  0.1031   
84  0.0149  0.0151  0.0156  ...  0.2007  0.2016  0.2023  0.2029  0.2037   

       610     608     606     604     602  
80  0.1411  0.1419  0.1426  0.1433  0.1443  
81  0.1648  0.1655  0.1662  0.1669  0.1678  
82  0.1469  0.1475  0.1481  0.1488  0.1497  
83  0.1034  0.1037  0.1041  0.1046  0.1052  
84  0.2045  0.2056  0.2066  0.2076  0.2089  

[5 rows x 607 columns]

8. Create a new variable called: ag_old and assigned to it all the samples that ar An. gambiae and older than 5 days. Print the first 7 rows

In [13]:
## print your answer here

ag_old = df_mosquitoes[(df_mosquitoes['Species'] == 'An. gambiae') & (df_mosquitoes['Age'] > 5)]

In [14]:
print(ag_old.head(7))

          Species  Age      Dataset     Status Country Rear Condition  \
1244  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1245  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1246  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1247  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1248  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1249  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   
1250  An. gambiae    7  Glasgow Lab  Blood fed       S             TL   

      StoTime    1800    1798    1796  ...     620     618     616     614  \
1244       10  0.0110  0.0111  0.0112  ...  0.1442  0.1446  0.1450  0.1455   
1245       10  0.0105  0.0106  0.0106  ...  0.1636  0.1642  0.1647  0.1652   
1246       10  0.0117  0.0118  0.0118  ...  0.1919  0.1926  0.1934  0.1942   
1247       10  0.0147  0.0149  0.0150  ...  0.2610  0.2620  0.2631  0.2641   
1248       10  0.0140  0.

9. Create a variable called X that have only wavelenghts from: 1800 - 602

In [15]:
## print your answer here

X = df_mosquitoes.loc[:,'1800':'602']
print(X)

        1800    1798    1796    1794    1792    1790    1788    1786    1784  \
0     0.0105  0.0106  0.0107  0.0109  0.0109  0.0108  0.0107  0.0108  0.0110   
1     0.0105  0.0106  0.0107  0.0109  0.0109  0.0108  0.0107  0.0108  0.0110   
2     0.0094  0.0094  0.0094  0.0093  0.0095  0.0099  0.0101  0.0102  0.0102   
3     0.0094  0.0094  0.0094  0.0093  0.0095  0.0099  0.0101  0.0102  0.0102   
4     0.0116  0.0117  0.0118  0.0119  0.0119  0.0118  0.0117  0.0117  0.0118   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
1659  0.0148  0.0150  0.0152  0.0155  0.0158  0.0160  0.0163  0.0166  0.0170   
1660  0.0148  0.0150  0.0152  0.0154  0.0157  0.0159  0.0161  0.0164  0.0167   
1661  0.0159  0.0161  0.0163  0.0164  0.0167  0.0169  0.0172  0.0175  0.0178   
1662  0.0159  0.0161  0.0163  0.0165  0.0168  0.0170  0.0173  0.0176  0.0179   
1663  0.0161  0.0163  0.0164  0.0166  0.0168  0.0171  0.0174  0.0177  0.0181   

        1782  ...     620     618     6

10. Select the column Age and assign it to a variable called y 



In [19]:
## print your answer here
y = df_mosquitoes['Age']
print(y)

0        1
1        1
2        1
3        1
4        1
        ..
1659    10
1660    10
1661    10
1662    10
1663    10
Name: Age, Length: 1664, dtype: int64


# Assesment part spectroscopy

## Frequency of molecular vibrations

During our lecture, we discussed that the frequency of vibration of a diatomic molecule is given by the following equation:

$$ f = \frac{1}{2 \pi} \sqrt{\frac{k}{\mu}}$$

where $k$ is the spring (or strength) constant and $\mu$ is the reduced mass of the two atoms calculated with the formula:

$$ \mu = \frac{m_1 m_2}{m_1 + m_2}$$

And as an example, I calculated the wavenumber in cm<sup>-1</sup> of the vibration of the C-H bond. I knew that the mass of carbon is 12 g/mol, strength constant of the C-H bond is 500 N/m and the Avogadro number is $N_A = 6.022 \cdot 10^{23}$ atoms/mol.

So I started calculating the mass of the hidrogen and carbon atoms

$$ m_H = \frac{1 \text{ g/mol}}{6.022 \cdot 10^{23} \text{ atoms/mol}} = 1.66 \cdot 10^{-24} \text{ g/atom} = 1.66 \cdot 10^{-27} \text{ kg/atom}$$


$$ m_C = \frac{12 \text{ g/mol}}{6.022 \cdot 10^{23} \text{ atoms/mol}} = 1.99 \cdot 10^{-23} \text{ g/atom} = 1.99 \cdot 10^{-26} \text{ kg/atom}$$

Then I calculated the reduced mass of the molecule

$$ \mu = \frac{1.66 \cdot 10^{-27} \text{ kg} \times 1.99 \cdot 10^{-26} \text{ kg}}{1.66 \cdot 10^{-27} \text{ kg}+  1.99 \cdot 10^{-26} \text{ kg}} = 1.531 \cdot 10^{-27} \text{ kg}$$

And with it and the spring constant, I could get the frequency of vibration of the molecule

$$ f_{CH} = \frac{1}{2 \pi} \sqrt{\frac{500 \text{ N/m}}{ 1.531 \cdot 10^{-27} \text{ kg}}} = 9.09 \cdot 10^{13} \text{ Hz}$$

To convert it into wavenumbers, I used the formula that we deducted from the properties of a wave:

$$\tilde{\nu} = \frac{1}{\lambda} = \frac{f}{c}$$

So

$$\tilde{\nu}_{CH} = \frac{9.09 \cdot 10^{13} \text{ s}^{-1}}{2.99 \cdot 10^8 \text{ m/s}} = 303 209 \text{ m}^{-1}$$

and in wavenumbers (cm<sup>-1</sup>):
$$303 209 \text{ m}^{-1} \times \frac{1 \text{ m}}{100 \text{ cm}} = 3032.09 \text{ cm}^{-1}$$


### Exercise

1. Using Python, write a function that can calculate the wavenumber of the vibration of a molecule for a given spring constant and the mass of the two atoms in the molecule. Use this function to calculate the vibration wavenumber of the following molecules C-H, C-C, C=C, C≡C and N≡N. 

*Please note how the wavenumbers of these molecules correspond to the areas designated in the literature for single, double, triple and hydrogen bonds.*

In [17]:
## hints

## you can use numpy to calculate the square root of any number by calling the function sqrt
print(np.sqrt(4))

## the value of pi can be also called using numpy

print(np.pi)

#Large or small numbers can be notated like this:
print(1.99e-26)

2.0
3.141592653589793
1.99e-26


Large or small numbers can be notated like this:

The number $1.99 \cdot 10^{-26}$ can be coded like this: 

```{python}
a = 1.99e-26
```

In [41]:
import numpy as np

def vibration_wavenumber(spring_constant, mass_M1, mass_M2):
    a = 6.022e23 # Avogadro's number
    
    mass_M1 = ((mass_M1 / a) / 1000) # in kg/atom
    mass_M2 = ((mass_M2 / a) / 1000) # in kg/atom
    
    reduced_mass = (mass_M1 * mass_M2) / (mass_M1 + mass_M2)
    waa = np.sqrt(spring_constant / reduced_mass)
    freq = (1 / (2 * np.pi)) * waa
    wavenumber = ((freq / 2.99e8) / 100)
    
    print("Vibration wavenumber: {:.2f} cm^-1".format(wavenumber))
    return wavenumber

# C-H:
spring_constant = float(input("Enter spring constant: "))  # in N/m
mass_M1 = float(input("Enter mass M1: "))                # Mass of first atom in atomic mass units (u)
mass_M2 = float(input("Enter mass M2: "))                # Mass of second atom in atomic mass units (u)

vibration_wavenumber(spring_constant, mass_M1, mass_M2)

Enter spring constant:  500
Enter mass M1:  1
Enter mass M2:  12


Vibration wavenumber: 3040.08 cm^-1


3040.082533616937

In [42]:
#C-C
spring_constant = float(input("Enter spring constant: "))  # in N/m
mass_M1 = float(input("Enter mass M1: "))                # Mass of first atom in atomic mass units (u)
mass_M2 = float(input("Enter mass M2: "))                # Mass of second atom in atomic mass units (u)

vibration_wavenumber(spring_constant, mass_M1, mass_M2)

Enter spring constant:  540
Enter mass M1:  12
Enter mass M2:  12


Vibration wavenumber: 1239.20 cm^-1


1239.1976284986865

In [43]:
#C=C
spring_constant = float(input("Enter spring constant: "))  # in N/m
mass_M1 = float(input("Enter mass M1: "))                # Mass of first atom in atomic mass units (u)
mass_M2 = float(input("Enter mass M2: "))                # Mass of second atom in atomic mass units (u)

vibration_wavenumber(spring_constant, mass_M1, mass_M2)

Enter spring constant:  1000
Enter mass M1:  12
Enter mass M2:  12


Vibration wavenumber: 1686.33 cm^-1


1686.3343779382067

In [44]:
#C≡C
spring_constant = float(input("Enter spring constant: "))  # in N/m
mass_M1 = float(input("Enter mass M1: "))                # Mass of first atom in atomic mass units (u)
mass_M2 = float(input("Enter mass M2: "))                # Mass of second atom in atomic mass units (u)

vibration_wavenumber(spring_constant, mass_M1, mass_M2)

Enter spring constant:  1500
Enter mass M1:  12
Enter mass M2:  12


Vibration wavenumber: 2065.33 cm^-1


2065.329380831144

In [45]:
#N≡N
spring_constant = float(input("Enter spring constant: "))  # in N/m
mass_M1 = float(input("Enter mass M1: "))                # Mass of first atom in atomic mass units (u)
mass_M2 = float(input("Enter mass M2: "))                # Mass of second atom in atomic mass units (u)

vibration_wavenumber(spring_constant, mass_M1, mass_M2)

Enter spring constant:  2287
Enter mass M1:  14
Enter mass M2:  14


Vibration wavenumber: 2361.04 cm^-1


2361.040197779518